blueprint:
  name: Grow Lights – Solar Noon Cycle
  description: >
    Controls grow lights 
  domain: automation

  input:
    grow_light_switch:
      name: Grow Light Switch
      selector:
        entity:
          domain: switch
    light_hours:
      name: daily grow hours
      selector: 
        duration: 
          enable_day: false
          enable_second: false
          allow_negative: false
      default: 12

mode: single

trigger:
  - platform: time_pattern
    minutes: "/1"
  - platform: homeassistant
    event: start

variables:
  light_switch: !input grow_light_switch

  now_ts: "{{ now().timestamp() }}"

  prev_noon: "{{ state_attr('sun.sun','previous_noon') }}"
  next_noon: "{{ state_attr('sun.sun','next_noon') }}"

  noon_ts: >
    {% if prev_noon is not none and next_noon is not none %}
      {{ as_timestamp(prev_noon if now_ts < as_timestamp(next_noon) else next_noon) }}
    {% else %}
      {{ as_timestamp(today_at('12:00')) }}
    {% endif %}

  half_window: "{{ (light_hours / 2) * 3600 }}"

  lights_on_ts: "{{ noon_ts - half_window }}"
  lights_off_ts: "{{ noon_ts + half_window }}"

action:
  - choose:
      # Turn lights ON
      - conditions:
          - condition: template
            value_template: >
              {{ now_ts >= lights_on_ts and now_ts < lights_off_ts }}
        sequence:
          - service: switch.turn_on
            target:
              entity_id: !input grow_light_switch

      # Turn lights OFF
      - conditions:
          - condition: template
            value_template: >
              {{ now_ts < lights_on_ts or now_ts >= lights_off_ts }}
        sequence:
          - service: switch.turn_off
            target:
              entity_id: !input grow_light_switch
