blueprint:
  name: Grow Lights – Solar Noon Cycle
  description: >
    Controls grow lights 
  domain: automation

  input:
    grow_light_switch:
      name: Grow Light Switch
      selector:
        entity:
          domain: switch
    light_hours:
      name: daily grow hours
      selector: 
        duration: 
          enable_day: false
          enable_second: false
          allow_negative: false
      default: 8
    centering_entity_prev: 
      name: time centering entity previous
      selector:
        entity: 
          filter:
            domain: datetime
    centering_entity_next: 
      name: time centering entity next
      selector:
        entity: 
          filter:
            domain: datetime

mode: single

trigger:
  - platform: time_pattern
    minutes: "/1"
  - platform: homeassistant
    event: start

variables:
  now_ts: "{{ now().timestamp() }}"

  centering_ts: >
      {{ as_timestamp(centering_entity_prev if now_ts < as_timestamp(centering_entity_nexxt) else centering_entity_next) }}

  half_window: "{{ (light_hours / 2) * 3600 }}"

  lights_on_ts: "{{ centering_ts - half_window }}"
  lights_off_ts: "{{ centering_ts + half_window }}"

action:
  - choose:
      # Turn lights ON
      - conditions:
          - condition: template
            value_template: >
              {{ now_ts >= lights_on_ts and now_ts < lights_off_ts }}
        sequence:
          - service: switch.turn_on
            target:
              entity_id: !input grow_light_switch

      # Turn lights OFF
      - conditions:
          - condition: template
            value_template: >
              {{ now_ts < lights_on_ts or now_ts >= lights_off_ts }}
        sequence:
          - service: switch.turn_off
            target:
              entity_id: !input grow_light_switch
